### ISSUE TITLE
Documentation on GitHub

### ISSUE THREAD

**Issue by djpeterso23662** [DieterVDW/arduino-lfo-adsr#2]
Hi Dieter!  I found your project on YouTube while considering how to make a looping envelope for LittleBits Synth Kit.  I found your documentation with difficulty through the http://archive.org website.  The LittleBits URL with your project page is no longer valid.  It would be great if you could transfer all you project description to the GitHub readme.md for your project, if you ever have free time.  It is really excellent, and is worth preserving. Best wishes, 
David

**Comment by DieterVDW** [comment]
Hi! Always a pleasant surprise when somebody seems to find something I made useful!

I found the old page on archive.org and created a README.md.

Cheers!
